### ISSUE TITLE
wrong argument

### ISSUE THREAD

**Issue by konetzed** [foxpass/foxpass-tools#21]
https://github.com/foxpass/foxpass-tools/blob/a65a3c7a3e8817af8c3782e5db766b97b68b7530/api/foxpass_delete_user.py#L25

Need to change, args.user to args.username otherwise following error is thrown. 

`
  File "./foxpass_delete_user.py", line 25, in main
    r = requests.delete(URL + ENDPOINT + args.user + '/', headers=header)
AttributeError: 'Namespace' object has no attribute 'user'
`

**Comment by ttheune** [comment]
Thanks for the report!
